name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET Env
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.203"

      - name: Restore Solution
        run: |
          dotnet restore
          dotnet tool restore --tool-manifest ./ModMenuAPI.Plugin/LethalCompany/.config/dotnet-tools.json
          dotnet tool restore --tool-manifest ./ModMenuAPI.Plugin/ContentWarning/.config/dotnet-tools.json

      - name: Pack Solution
        run: |
          dotnet build --configuration Release

      - name: Upload Thunderstore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: ./ModMenuAPI.Plugin/*/Thunderstore/Packages/*.zip
