name: Release

on:
  release:
    types: [released, prereleased]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
          submodules: true

      - name: Setup .NET Env
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.203"

      - name: Restore Solution
        run: |
          dotnet restore
          dotnet tool restore --tool-manifest ./ModMenuAPI.Plugin/LethalCompany/.config/dotnet-tools.json
          dotnet tool restore --tool-manifest ./ModMenuAPI.Plugin/ContentWarning/.config/dotnet-tools.json

      - name: Build Solution
        run: |
          dotnet build --configuration Release

      - name: Upload Thunderstore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: ./ModMenuAPI.Plugin/*/Thunderstore/Packages/*.zip

  upload-release-artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Thunderstore Artifact
        uses: actions/download-artifact@v4
        with:
          name: thunderstore-build
          path: ./ModMenuAPI.Plugin/*/Thunderstore/Packages/

      - name: Display structure of files
        run: ls -R

      - name: Upload Plugin.LC to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./ModMenuAPI.Plugin/LethalCompany/Thunderstore/Packages/*.zip

      - name: Upload Plugin.CW to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./ModMenuAPI.Plugin/ContentWarning/Thunderstore/Packages/*.zip

#   deploy-thunderstore:
#     if: ${{ github.event.release.prerelease == false }}
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Download Thunderstore Artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: thunderstore-build
#           path: ./ModMenuAPI/Thunderstore/Packages/

#       - name: Restore Tools
#         run: |
#           dotnet tool restore

#       - name: Publishing to Thunderstore
#         env:
#           TCLI_AUTH_TOKEN: ${{ secrets.THUNDERSTORE_API_TOKEN }}
#         run: |
#           dotnet tcli publish --config-path ./ModMenuAPI/Thunderstore/thunderstore.toml --file ./ModMenuAPI/Thunderstore/Packages/*.zip